# MoveIt-specific simulation settings
moveit_sim_hw_interface:
  joint_model_group: controllers_initial_group_
  joint_model_group_pose: controllers_initial_pose_

# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  sim_control_mode: 1 # 0: position, 1: velocity

# Publish joint_states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

kuka_arm_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6
  gains:
    joint_a1: { p: 1, d: 1, i: 0, i_clamp: 1 }
    joint_a2: { p: 1, d: 1, i: 0, i_clamp: 1 }
    joint_a3: { p: 1, d: 1, i: 0, i_clamp: 1 }
    joint_a4: { p: 1, d: 1, i: 0, i_clamp: 1 }
    joint_a5: { p: 1, d: 1, i: 0, i_clamp: 1 }
    joint_a6: { p: 1, d: 1, i: 0, i_clamp: 1 }
  constraints:
    goal_time: 2.0
  state_publish_rate: 25
  
controller_list:
  - name: kuka_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_a1
      - joint_a2
      - joint_a3
      - joint_a4
      - joint_a5
      - joint_a6
    
