# Publish all joint states
  joint_state-controller:
    type: joint_state-controller/JointStateController
    publish_rate: 50
  
# position controllers
  link_1_controller:
    type: effort_controller/JointEffortController
    joint: joint_a1
    #pid: {p: 5, i: 5, d: 5}
  link_2_controller:
    type: effort_controller/JointEffortController
    joint: joint_a2
    #pid: {p: 5, i: 5, d: 5}
  link_3_controller:
    type: effort_controller/JointEffortController
    joint: joint_a3
    #pid: {p: 5, i: 5, d: 5}
  link_4_controller:
    type: effort_controller/JointEffortController
    joint: joint_a4
    #pid: {p: 5, i: 5, d: 5}
  link_5_controller:
    type: effort_controller/JointEffortController
    joint: joint_a5
    #pid: {p: 5, i: 5, d: 5}
  link_6_controller:
    type: effort_controller/JointEffortController
    joint: joint_a6
    #pid: {p: 5, i: 5, d: 5}
